### PR TITLE
Rename ExceptionInterface to Exception

### PR DESCRIPTION
**Pull request by michalbundyra**
Renamed `ExceptionInterface` to `Exception`.
This is consistency fix, please see for example:
https://github.com/zendframework/zend-expressive-hal/blob/master/src/Exception/Exception.php

Updated also doc comment to point to the proper repository.

### CODE REVIEW

**Comment by weierophinney** [comment]
We opened an RFC from this, as the work done in zend-expressive-hal was a bit of a shocker for many with regards to interface naming: https://discourse.zendframework.com/t/interface-suffix-take-it-or-leave-it/259/

The consensus at this time is that the majority of respondents on that thread would prefer the `Interface` suffix. While I don't necessarily agree, there is one compelling argument: consistency with existing components. We have over 50 existing components that all use the `Interface` suffix, and introducing a new naming convention at this time will lead to confusion by maintainers and consumers alike.

**Comment by michalbundyra** [comment]
@weierophinney thanks for the note, I've missed that.
Are we going to change it then in `zend-expressive-hal` or there it will stay as it is?

**Comment by weierophinney** [comment]
We're going to change it on zend-expressive-hal.

**Comment by michalbundyra** [comment]
@weierophinney 
> We're going to change it on zend-expressive-hal.

Ok, then. Here is PR https://github.com/zendframework/zend-expressive-hal/pull/16

**Pull request closed without merging**
